services:
  alert-streaming:
    build: .
    container_name: alert-streaming
    environment:
      SPARK_MASTER: local[*]
      KAFKA_BROKERS: kafka:9092
      TOPIC_GEOLOCATION: topic.geolocation
      TOPIC_ALERT: topic.alert
      CHECKPOINT_DIR: /opt/checkpoints/alerts
      RISK_THRESHOLD: "0.10"
      STARTING_OFFSETS: latest
      TRIGGER_INTERVAL: "10 seconds"
      APP_NAME: danger-zone-streaming
    volumes:
      - spark-checkpoints:/opt/checkpoints
    restart: unless-stopped
    networks:
      - rides-net

networks:
  rides-net:
    external: true
    name: rides_simulator_default

volumes:
  spark-checkpoints:
